### PR TITLE
Add binary hash for 13.6.4

### PR DESCRIPTION
**Pull request by xChickens**
Fixed linting to merge change quicker

### CODE REVIEW

**Comment by 0xdevalias** [comment]
- Duplicate of https://github.com/beeper/mac-registration-provider/pull/32 (?)

**Comment by xChickens** [comment]
> * Duplicate of [Add support for 13.6.4 #32](https://github.com/beeper/mac-registration-provider/pull/32)
> 
> 
> The changes look the same, so I assume this PR can probably be closed in favour of that one (which has more in-depth discussion/context/etc)

I'm just trying to get the change fixed more quickly and not have 4 commits for a 4 line change

**Comment by 0xdevalias** [comment]
> I'm just trying to get the change fixed more quickly and not have 4 commits for a 4 line change

Generally speaking, creating a new PR like this is considered creating more noise/spam than continuing on the original; and is unlikely to speed things up.

I can't speak for this repo as I'm not a maintainer, but generally either 4 commits aren't an issue, you could squash/force push them to the same branch/PR anyway, or they could be made a single commit by squash merging that original PR.

**Comment by xChickens** [comment]
> > I'm just trying to get the change fixed more quickly and not have 4 commits for a 4 line change
> 
> Generally speaking, creating a new PR like this is considered creating more noise/spam than continuing on the original; and is unlikely to speed things up.
> 
> I can't speak for this repo as I'm not a maintainer, but generally either 4 commits aren't an issue, you could squash/force push them to the same branch/PR anyway, or they could be made a single commit by squash merging that original PR.
> 
> It's also generally not ideal to make a PR from a 'main' branch rather than a feature branch:
> 
> image

For your first point, that would be true if it was a complete duplicate. It isn't, as the other PR has had a lint failure for over a week, which implies the other developer is not that active. If he doesn't correct the PR or come back at all then the PR could remain indefinitely in limbo.

Your second point is fair, but the fact that it took 4 commits and will take another to fix the lint has implications that the developer does not entirely know what they're doing and could easily do a fast forward, rebase, or normal merge, adding all the commits. Extremely common when people aren't experienced with git.

Third point, does it really matter that I didn't use a feature branch? Like it's my own work of the repo, I can organize it however I want. I don't expect to use main in any way so I could literally rename the main branch to whatever and set it as the default.

**Comment by xChickens** [comment]
Also this issue is specifically affecting my as the max I have access to is 13.6.4. I can't compile the source code since I only have Linux dev environments.

**Comment by 0xdevalias** [comment]
> If he doesn't correct the PR or come back at all then the PR could remain indefinitely in limbo.

@xChickens That's fair. For some reason I thought both PR's were yours; clearly I didn't look closely enough.

**Pull request merged**
